### ISSUE TITLE
Support for changing close/maximize/minimize buttons

### ISSUE THREAD

**Issue by caioolivv** [ArtyIF/AdwCustomizer#20]
Is it or will it be possible to change the buttons and their colors with AdwCustomizer?

**Comment by ArtyIF** [comment]
You can use the custom CSS field to change how they look.18:48, July 26, 2022, Caio Lima de Oliveira ***@***.***>:
Is it or will it be possible to change the buttons and their colors with AdwCustomizer?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by ArtyIF** [comment]
In particular, if you want to hide the circles from the window controls, use:

```css
windowcontrols image {
    background-color: transparent;
}
    
/* If you want to keep the circles when you hover: */
windowcontrols image:hover {
    background-color: alpha(@headerbar_fg_color, 0.07);
}

/* When the buttons are pushed down: */
windowcontrols image:active {
    background-color: alpha(@headerbar_fg_color, 0.16);
}
```

The alpha values are based on values the flat buttons use.
