### ISSUE TITLE
Support for rafaelmardojai/firefox-gnome-theme

### ISSUE THREAD

**Issue by ZechariahB** [ArtyIF/AdwCustomizer#9]
Since Firefox Gnome Theme recently followed GTK4 / Libadwaita style, it would make sense to expand this software to optionally edit the theme according to the color preferences set by the user so that colors can be consistent.

**Comment by ArtyIF** [comment]
Wait, it doesn't follow the set colors? I thought it did.19:26, July 21, 2022, ZechariahB ***@***.***>:
Since Firefox Gnome Theme recently followed GTK4 / Libadwaita style, it would make sense to expand this software to optionally edit the theme according to the color preferences set by the user so that colors can be consistent.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by ArtyIF** [comment]
I checked the source code for the extension. It's pretty confusing, some help and potential overwrites are going to be required.

**Comment by daudix-UFO** [comment]
This theme uses colors from "theme/colors/light.css", we need to create/edit this files
https://github.com/rafaelmardojai/firefox-gnome-theme/tree/master/theme/colors

**Comment by ArtyIF** [comment]
> This theme uses colors from [theme/colors/](https://github.com/rafaelmardojai/firefox-gnome-theme/tree/master/theme/colors), we need to create/edit this files

The syntax is heavily different from libadwaita's, so more work will be required for that

**Comment by 0xMRTT** [comment]
See https://github.com/GradienceTeam/gradience_firefox_gnome_theme, for a WIP plugin

**Comment by aspizu** [comment]
```css
:root {
    --d_1: #010409;
    --d_2: #0c1015;
    --d_3: #0d1117;
    --d_4: #2d3139;
    --l_1: #7d858d;
    --l_2: #959da5;
    --l_3: #b4bcc4;
    --l_4: #c9d1d9;

    --bg: #010409;
    --fg: #f0f6fc;

    --blk: #0c1015;
    --red: #ff7b72;
    --grn: #3fb950;
    --ylw: #d29922;
    --blu: #58a6ff;
    --pnk: #bc8cff;
    --cyn: #39c5cf;
    --wht: #b4bcc4;
    --b_blk: #2d3139;
    --b_red: #ffa198;
    --b_grn: #56d364;
    --b_ylw: #e3b341;
    --b_blu: #79c0ff;
    --b_pnk: #d2a8ff;
    --b_cyn: #56d4dd;
    --b_wht: #f0f6fc;
}

:root {
    --gnome-browser-before-load-background:        var(--s_1);
    --gnome-accent-bg:                             var(--blu);
    --gnome-accent:                                var(--b_blu);
    --gnome-toolbar-background:                    var(--s_1);
    --gnome-toolbar-color:                         var(--l_4);
    --gnome-toolbar-icon-fill:                     var(--l_3);
    --gnome-inactive-toolbar-color:                var(--l_2);
    --gnome-inactive-toolbar-border-color:         var(--d_4);
    --gnome-inactive-toolbar-icon-fill:            var(--l_1);
    --gnome-menu-background:                       var(--d_3);
    --gnome-headerbar-background:                  var(--d_1);
    --gnome-button-destructive-action-background:  var(--red);
    --gnome-entry-color:                           var(--l_4);
    --gnome-inactive-entry-color:                  var(--l_3);
    --gnome-switch-slider-background:              var(--l_3);
    --gnome-switch-active-slider-background:       var(--l_4);
    --gnome-inactive-tabbar-tab-background:        var(--d_1);
    --gnome-inactive-tabbar-tab-active-background: var(--d_1);
    --gnome-tabbar-tab-background:                 var(--d_1);
    --gnome-tabbar-tab-hover-background:           var(--d_2);
    --gnome-tabbar-tab-active-background:          var(--d_2);
    --gnome-tabbar-tab-active-hover-background:    var(--d_3);
    --gnome-tabbar-tab-active-background-contrast: var(--d_4);
}
```
